# Site Settings
title: Sandro Torres | Desenvolvedor Front-end
email: sj.torres@live.com
description: Blog criado para compartilhar dicas e tutoriais de códigos, tanto na área de Front-end como Back-end.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sjtorres.github.io/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Torres
user_description: Apaixonado por tecnologia.
disqus_username: sjtorres

# Social Media
# Remove the item if you don't need it
github_username: sjtorres
facebook_username: SandroJ.Torres
twitter_username: SandroJT
instagram_username: sj.torres
linkedin_username: linkedin_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Início
    url: /
  - title: Sobre
    url: /about/
  - title: Portfólio
    url: /portfolio/
  - title: Contato
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
